export const games = [
    {
        id:1,
        name: 'Vampire: The Masquerade - Bloodlines 2',
        poster: '/game_vimpire_poster.jpg',
        rating: 7.8,
        date: '2023-04-27',
        description: 'Sired in an act of vampire insurrection, your existence ignites the war for Seattles blood trade. Enter uneasy alliances with the creatures who control the city and uncover the sprawling conspiracy which plunged Seattle into a bloody civil war between powerful vampire factions',
        href:"https://store.epicgames.com/ru/p/vampire-the-masquerade-bloodlines-2?lang=en-us&sessioninvalidated=true",
        platform: ["PlayStation 5", "PC", "Xbox One"],
        images: [
            '/images/1/vampire1.jpg',
            '/images/1/vampire2.jpg',
            '/images/1/vampire3.jpg',
            '/images/1/vampire4.jpg',
            '/images/1/vampire5.jpg',
            '/images/1/vampire6.jpg',
        ]
    },
    {
        id:2,
        name: 'Barotrauma',
        poster: '/game_barotrrauma_poster.jpg',
        rating: 6.8,
        date: '2022-09-17',
        description: 'Overcome crisis and the unrelenting pressure of a frozen ocean. In Barotrauma you`re a submarine crew member beneath the ice of Jupiter`s moon Europa. Flee or fight alien lifeforms, explore a strange new world, command your crew, and craft equipment in a tense 2d co-op experience.Key FeaturesCommand and manage your submarine and its various systems in adrenaline-filled co-operative gameplay.',
        href:"https://store.steampowered.com/app/602960/Barotrauma/",
        platform: ["Linux", "macOS", "PC"],
        images: [
            '/images/2/barotrrauma1.jpg',
            '/images/2/barotrrauma2.jpg',
            '/images/2/barotrrauma3.jpg',
            '/images/2/barotrrauma4.jpg',
            '/images/2/barotrrauma5.jpg',
            '/images/2/barotrrauma6.jpg',
        ]
    },
    {
        id:3,
        name: 'S.T.A.L.K.E.R. 2: Heart of Chornobyl',
        poster: '/game_stalker_poster.jpg',
        rating: 7.2,
        date: '2023-11-07',
        description: "S.T.A.L.K.E.R. 2 is a brand-new entry in the legendary series, enjoyed by millions of players worldwide. The explosive combination of first-person shooter, immersive sim and horror is back. It’s the ultimate S.T.A.L.K.E.R. experience of unprecedented scale, advanced graphics, freedom of choices and the thickest atmosphere of a deadly adventure",
        href:"https://www.gog.com/en/game/stalker_2_heart_of_chornobyl_standard_edition",
        platform: ["PC", "Xbox One"],
        images: [
            '/images/3/stalker1.jpg',
            '/images/3/stalker2.jpg',
            '/images/3/stalker3.jpg',
            '/images/3/stalker4.jpg',
            '/images/3/stalker5.jpg',
            '/images/3/stalker6.jpg',
        ]
    },
    {
        id:4,
        name: 'Hogwarts Legacy',
        poster: '/game_hogwarts_poster.jpg',
        rating: 4.8,
        date: '2021-08-22',
        description: "Hogwarts Legacy is an immersive, open-world action RPG set in the world first introduced in the Harry Potter books. Now you can take control of the action and be at the center of your own adventure in the wizarding world. Embark on a journey through familiar and new locations as you explore and discover fantastic beasts, customize your character and craft potions, master spell casting, upgrade talents, and become the wizard you want to be. Experience Hogwarts in the 1800s",
        href:"https://store.playstation.com/en-us/concept/232447",
        platform: ["PC", "PlayStation 5", "Nintendo Switch", "Xbox One"],
        images: [
            '/images/4/hogwarts1.jpg',
            '/images/4/hogwarts2.jpg',
            '/images/4/hogwarts3.jpg',
            '/images/4/hogwarts4.jpg',
            '/images/4/hogwarts5.jpg',
            '/images/4/hogwarts6.jpg',
        ]
    },
    {
        id:5,
        name: 'Starfield',
        poster: '/game_starfield_poster.jpg',
        rating: 5.2,
        date: '2023-01-11',
        description: "Starfield is the first new universe in 25 years from Bethesda Game Studios, the award-winning creators of The Elder Scrolls V: Skyrim and Fallout 4. In this next generation role-playing game set amongst the stars, create any character you want and explore with unparalleled freedom as you embark on an epic journey to answer humanity’s greatest mystery.",
        href:"https://store.steampowered.com/app/1716740/Starfield/",
        platform: ["PC", "Xbox One"],
        images: [
            '/images/5/starfield1.jpg',
            '/images/5/starfield2.jpg',
            '/images/5/starfield3.jpg',
            '/images/5/starfield4.jpg',
            '/images/5/starfield5.jpg',
            '/images/5/starfield6.jpg',
        ]
    },
    {
        id:6,
        name: 'Atomic Heart',
        poster: '/game_atomic_poster.jpg',
        rating: 9.2,
        date: '2023-09-28',
        description: "Atomic Heart is an adventure first-person shooter, events of which unfolds in an alternate universe during the high noon of the Soviet Union. The principal character of the game is a special agent P-3, who after an unsuccessful landing on enterprise '3826' is trying to figure out what went wrong and to clear up a factory from went mad robots.",
        href:"https://store.steampowered.com/app/668580/",
        platform: ["PlayStation 5", "PC", "Xbox One"],
        images: [
            '/images/6/atomic1.jpg',
            '/images/6/atomic2.jpg',
            '/images/6/atomic3.jpg',
            '/images/6/atomic4.jpg',
            '/images/6/atomic5.jpg',
            '/images/6/atomic6.jpg',
        ]
    },
]; 